version: '3'
services:
  parse:
    image: albahoo/parse-server-with-oss-adapter
    environment:
      - PARSE_SERVER_APPLICATION_ID=parse
      - PARSE_SERVER_MASTER_KEY=${PARSE_SERVER_MASTER_KEY-parse@master123!}
      - PARSE_SERVER_DATABASE_URI=${PARSE_SERVER_DATABASE_URI-postgres://Alba@host.docker.internal/parse_server_development}
      - PARSE_SERVER_MOUNT_PATH=/parse
      - PARSE_SERVER_FILES_ADAPTER=parse-server-oss-adapter2
      - OSS_ACCESS_KEY=${PARSE_OSS_ACCESS_KEY}
      - OSS_SECRET_KEY=${PARSE_OSS_SECRET_KEY}
      - OSS_BUCKET=${PARSE_OSS_BUCKET-tenty-parse-files}
      - OSS_REGION=oss-cn-hangzhou

    ports:
      - '1337:1337'
    volumes:
      - myapp:/parse-server-app

  parse-dashboard:
    image: parseplatform/parse-dashboard
    ports:
      - '4040:4040'
    environment:
#      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
      - PARSE_DASHBOARD_TRUST_PROXY=1
      - PARSE_DASHBOARD_COOKIE_SESSION_SECRET=AB8849B6-D725-4A75-AA73-AB7103F0363F
      - PARSE_DASHBOARD_SERVER_URL=${PARSE_DASHBOARD_SERVER_URL-http://localhost:1337/parse}
      - PARSE_DASHBOARD_MASTER_KEY=${PARSE_SERVER_MASTER_KEY-parse@master123!}
      - PARSE_DASHBOARD_APP_ID=parse
      - PARSE_DASHBOARD_APP_NAME=AlbaApp
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=password
      - MOUNT_PATH=/dashboard/
    command: parse-dashboard --dev
    depends_on:
      - parse
volumes:
  myapp:
